CREATE TABLE IF NOT EXISTS personal(
   id INT NOT NULL AUTO_INCREMENT,
   name VARCHAR(50) NOT NULL,
   role ENUM('CASHIER', 'KITCHEN', 'ADMIN') NOT NULL,
   phone VARCHAR(20) NOT NULL,
   active TINYINT UNSIGNED,
   PRIMARY KEY (id),
   UNIQUE(phone)
);